import dev.p2pkit.build.GitCommitValueSource
import dev.p2pkit.build.GitDirtyValueSource
import dev.p2pkit.build.VerifyXcframeworkProvenanceTask
import dev.p2pkit.build.WriteXcframeworkProvenanceTask
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    `maven-publish`
}

kotlin {
    // Bundles all three iOS arch slices (device arm64 + sim arm64 + sim x64)
    // into a single .xcframework so the Xcode app at iosApp/ can pick the
    // right slice automatically based on SDKROOT. Generated by the Gradle
    // task `assembleP2pKitSharedXCFramework`.
    val xcf = XCFramework("P2pKitShared")

    jvmToolchain(17)
    jvm()

    android {
        namespace = "dev.p2pkit.transport.lan"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    // iOS LAN/TCP via Bonjour + Network.framework. Same public API as
    // JVM/Android (`transports { lan() }`), backed by NWBrowser / NWListener
    // / NWConnection. Requires iOS 13+; minimum is enforced by the Network
    // framework symbols themselves.
    val iosTargets = listOf(iosX64(), iosArm64(), iosSimulatorArm64())
    iosTargets.forEach { target ->
        // Wraps NW_PARAMETERS_DISABLE_PROTOCOL / NW_PARAMETERS_DEFAULT_CONFIGURATION
        // in a static-inline C helper so Kotlin never has to box those
        // void-returning block globals as kotlin.Any. See
        // src/nativeInterop/cinterop/p2pkit_nw.h for the rationale.
        target.compilations.getByName("main") {
            cinterops.create("p2pkit_nw") {
                defFile = project.file("src/nativeInterop/cinterop/p2pkit_nw.def")
            }
        }
        // Sample-app consumers want a single Swift-importable framework that
        // bundles :p2p-core's types alongside the LAN transport extension.
        // `export(project(":p2p-core"))` lifts the dependency's public API
        // into the framework's Swift surface so consumers can reference
        // P2pKit / AppId / Peer / P2pMessage / ... directly.
        // Run `./gradlew :p2p-transport-lan:linkDebugFrameworkIosSimulatorArm64`
        // (or `linkReleaseFrameworkIosArm64` for device builds) and drop the
        // resulting `.framework` into Xcode — see the maintained sample at iosApp/.
        target.binaries.framework {
            baseName = "P2pKitShared"
            isStatic = false
            export(project(":p2p-core"))
            xcf.add(this)
        }
    }

    sourceSets {
        commonMain.dependencies {
            // `api` rather than `implementation`: the iOS framework's
            // `export(project(":p2p-core"))` above requires the dependency to
            // be in the public API surface. It also matters for JVM/Android
            // consumers — `api` puts p2p-core's public types (P2pKit, Peer,
            // P2pSession, …) on their compile classpath, which the transport's
            // own public `lan()` DSL returns; `implementation` would hide them.
            api(project(":p2p-core"))
            api(libs.kotlinx.coroutines.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
        jvmMain.dependencies {
            implementation(libs.jmdns)
        }
        // Task #25 (v0.5): Android uses JmDNS instead of NsdManager to own the
        // mDNS cache in-process and unblock per-peer record invalidation that
        // the system NSD daemon does not expose. Pure-Java jar, no native
        // bits, so the same artifact as jvmMain.
        androidMain.dependencies {
            implementation(libs.jmdns)
        }
    }
}

// XCFramework provenance is a typed post-assembly task with declared inputs
// and outputs. Deleting any sidecar reruns the writer; source/config changes
// (including untracked files) update the fingerprint; and an unresolvable git
// identity fails instead of writing "unknown". A normal dependsOn edge orders
// the writer after successful assembly, so a failed framework is not attested.
val xcframeworkProvenancePaths = listOf(
    "buildSrc/src/main/java/dev/p2pkit/build",
    "p2p-core/src",
    "p2p-transport-lan/src",
    "p2p-core/build.gradle.kts",
    "p2p-transport-lan/build.gradle.kts",
    "build.gradle.kts",
    "settings.gradle.kts",
    "gradle.properties",
    "gradle/libs.versions.toml",
    "gradle/wrapper/gradle-wrapper.properties",
)
val xcframeworkProvenanceInputs = files(
    xcframeworkProvenancePaths.map(rootProject::file),
).asFileTree
val xcframeworkCommit = providers.of(GitCommitValueSource::class) {
    parameters.rootDirectory.set(rootProject.layout.projectDirectory)
}
val xcframeworkDirty = providers.of(GitDirtyValueSource::class) {
    parameters.rootDirectory.set(rootProject.layout.projectDirectory)
    parameters.relevantPaths.set(xcframeworkProvenancePaths)
}

fun registerXcframeworkProvenanceVerification(config: String) {
    val capitalized = config.replaceFirstChar(Char::uppercaseChar)
    val outDir = layout.buildDirectory.dir("XCFrameworks/$config")
    val frameworkBinaries = outDir.map { directory ->
        listOf(
            directory.file("P2pKitShared.xcframework/ios-arm64/P2pKitShared.framework/P2pKitShared").asFile,
            directory.file("P2pKitShared.xcframework/ios-arm64_x86_64-simulator/P2pKitShared.framework/P2pKitShared").asFile,
        )
    }
    val writeTask = tasks.register<WriteXcframeworkProvenanceTask>(
        "writeP2pKitShared${capitalized}XCFrameworkProvenance",
    ) {
        group = "build"
        description = "Writes declared provenance for the $config P2pKitShared XCFramework."
        dependsOn("assembleP2pKitShared${capitalized}XCFramework")
        provenanceInputs.from(xcframeworkProvenanceInputs)
        this.frameworkBinaries.from(frameworkBinaries)
        rootDirectory.set(rootProject.layout.projectDirectory)
        sourceCommit.set(xcframeworkCommit)
        relevantSourceDirty.set(xcframeworkDirty)
        commitFile.set(outDir.map { it.file("BUILD_COMMIT.txt") })
        stateFile.set(outDir.map { it.file("BUILD_SOURCE_STATE.txt") })
        fingerprintFile.set(outDir.map { it.file("BUILD_INPUTS_SHA256.txt") })
    }
    tasks.register<VerifyXcframeworkProvenanceTask>(
        "verifyP2pKitShared${capitalized}XCFrameworkProvenance",
    ) {
        group = "verification"
        description = "Verifies the $config P2pKitShared XCFramework provenance sidecars."
        dependsOn(writeTask)
        provenanceInputs.from(xcframeworkProvenanceInputs)
        this.frameworkBinaries.from(frameworkBinaries)
        rootDirectory.set(rootProject.layout.projectDirectory)
        sourceCommit.set(xcframeworkCommit)
        relevantSourceDirty.set(xcframeworkDirty)
        commitFile.set(writeTask.flatMap { it.commitFile })
        stateFile.set(writeTask.flatMap { it.stateFile })
        fingerprintFile.set(writeTask.flatMap { it.fingerprintFile })
    }
}

registerXcframeworkProvenanceVerification("release")
registerXcframeworkProvenanceVerification("debug")

// Maven publishing (fixes no-publishing-plugin / no-pom-metadata). See
// :p2p-core build for rationale. Auto-created KMP publications; POM enriched
// for Central-readiness; signing wired centrally in the root build (conditional
// on a PGP key being supplied).
publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name.set("P2pKit ${project.name}")
            description.set("P2pKit LAN transport — Bonjour/JmDNS discovery + TCP data over Network.framework/sockets.")
            url.set("https://github.com/Apdelrahman1911/P2pKit")
            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }
            developers {
                developer {
                    id.set("Apdelrahman1911")
                    name.set("Abdelrahman")
                }
            }
            scm {
                url.set("https://github.com/Apdelrahman1911/P2pKit")
                connection.set("scm:git:https://github.com/Apdelrahman1911/P2pKit.git")
                developerConnection.set("scm:git:ssh://git@github.com/Apdelrahman1911/P2pKit.git")
            }
        }
    }
}
