import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
}

// V0.4-PROVENANCE (L3): write a BUILD_COMMIT.txt sidecar file alongside
// the freshly-assembled XCFramework so the Xcode pre-build script can
// validate the framework's commit hash against `git rev-parse HEAD`
// before allowing the iOS app to compile against it. Wired as a
// `finalizedBy` on both the Release and Debug XCFramework assembly
// tasks below.
val writeXcframeworkCommit by tasks.registering {
    val rootDir = rootProject.projectDir
    val outDirs = listOf(
        layout.buildDirectory.dir("XCFrameworks/release"),
        layout.buildDirectory.dir("XCFrameworks/debug")
    )
    outputs.upToDateWhen { false }
    doLast {
        fun git(vararg args: String): String = try {
            val p = ProcessBuilder("git", *args)
                .directory(rootDir)
                .redirectErrorStream(true)
                .start()
            val out = p.inputStream.bufferedReader().readText().trim()
            if (p.waitFor() == 0) out else ""
        } catch (_: Exception) {
            ""
        }
        val commit = git("rev-parse", "HEAD").ifBlank { "unknown" }
        outDirs.forEach { dirProvider ->
            val dir = dirProvider.get().asFile
            if (dir.exists()) {
                dir.resolve("BUILD_COMMIT.txt").writeText(commit + "\n")
            }
        }
    }
}

kotlin {
    // Bundles all three iOS arch slices (device arm64 + sim arm64 + sim x64)
    // into a single .xcframework so the Xcode app at iosApp/ can pick the
    // right slice automatically based on SDKROOT. Generated by the Gradle
    // task `assembleP2pKitSharedXCFramework`.
    val xcf = XCFramework("P2pKitShared")

    jvmToolchain(17)
    jvm()

    android {
        namespace = "dev.p2pkit.transport.lan"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    // v0.3.0-dev: iOS LAN/TCP via Bonjour + Network.framework. Same public API
    // as JVM/Android (`transports { lan() }`), backed by NWBrowser / NWListener
    // / NWConnection. Requires iOS 13+; minimum is enforced by the Network
    // framework symbols themselves.
    val iosTargets = listOf(iosX64(), iosArm64(), iosSimulatorArm64())
    iosTargets.forEach { target ->
        // Wraps NW_PARAMETERS_DISABLE_PROTOCOL / NW_PARAMETERS_DEFAULT_CONFIGURATION
        // in a static-inline C helper so Kotlin never has to box those
        // void-returning block globals as kotlin.Any. See
        // src/nativeInterop/cinterop/p2pkit_nw.h for the rationale.
        target.compilations.getByName("main") {
            cinterops.create("p2pkit_nw") {
                defFile = project.file("src/nativeInterop/cinterop/p2pkit_nw.def")
            }
        }
        // Sample-app consumers want a single Swift-importable framework that
        // bundles :p2p-core's types alongside the LAN transport extension.
        // `export(project(":p2p-core"))` lifts the dependency's public API
        // into the framework's Swift surface so consumers can reference
        // P2pKit / AppId / Peer / P2pMessage / ... directly.
        // Run `./gradlew :p2p-transport-lan:linkDebugFrameworkIosSimulatorArm64`
        // (or `linkReleaseFrameworkIosArm64` for device builds) and drop the
        // resulting `.framework` into Xcode — see docs/ios-sample-app/.
        target.binaries.framework {
            baseName = "P2pKitShared"
            isStatic = false
            export(project(":p2p-core"))
            xcf.add(this)
        }
    }

    sourceSets {
        commonMain.dependencies {
            // `api` rather than `implementation`: the iOS framework's
            // `export(project(":p2p-core"))` above requires the dependency to
            // be in the public API surface. Has no effect on the JVM/Android
            // consumers (their build doesn't surface it differently).
            api(project(":p2p-core"))
            implementation(libs.kotlinx.coroutines.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
        jvmMain.dependencies {
            implementation(libs.jmdns)
        }
    }
}

// Make every XCFramework-assembly task write the BUILD_COMMIT.txt sidecar.
// V0.4-PROVENANCE (L3): the Xcode pre-build script reads this file to
// validate the deployed framework matches `git rev-parse HEAD` before
// allowing the iOS app to compile against it.
afterEvaluate {
    tasks.matching {
        it.name.startsWith("assemble") && it.name.contains("XCFramework")
    }.configureEach {
        finalizedBy(writeXcframeworkCommit)
    }
}
