import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    `maven-publish`
}

kotlin {
    // Bundles all three iOS arch slices (device arm64 + sim arm64 + sim x64)
    // into a single .xcframework so the Xcode app at iosApp/ can pick the
    // right slice automatically based on SDKROOT. Generated by the Gradle
    // task `assembleP2pKitSharedXCFramework`.
    val xcf = XCFramework("P2pKitShared")

    jvmToolchain(17)
    jvm()

    android {
        namespace = "dev.p2pkit.transport.lan"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    // iOS LAN/TCP via Bonjour + Network.framework. Same public API as
    // JVM/Android (`transports { lan() }`), backed by NWBrowser / NWListener
    // / NWConnection. Requires iOS 13+; minimum is enforced by the Network
    // framework symbols themselves.
    val iosTargets = listOf(iosX64(), iosArm64(), iosSimulatorArm64())
    iosTargets.forEach { target ->
        // Wraps NW_PARAMETERS_DISABLE_PROTOCOL / NW_PARAMETERS_DEFAULT_CONFIGURATION
        // in a static-inline C helper so Kotlin never has to box those
        // void-returning block globals as kotlin.Any. See
        // src/nativeInterop/cinterop/p2pkit_nw.h for the rationale.
        target.compilations.getByName("main") {
            cinterops.create("p2pkit_nw") {
                defFile = project.file("src/nativeInterop/cinterop/p2pkit_nw.def")
            }
        }
        // Sample-app consumers want a single Swift-importable framework that
        // bundles :p2p-core's types alongside the LAN transport extension.
        // `export(project(":p2p-core"))` lifts the dependency's public API
        // into the framework's Swift surface so consumers can reference
        // P2pKit / AppId / Peer / P2pMessage / ... directly.
        // Run `./gradlew :p2p-transport-lan:linkDebugFrameworkIosSimulatorArm64`
        // (or `linkReleaseFrameworkIosArm64` for device builds) and drop the
        // resulting `.framework` into Xcode — see docs/ios-sample-app/.
        target.binaries.framework {
            baseName = "P2pKitShared"
            isStatic = false
            export(project(":p2p-core"))
            xcf.add(this)
        }
    }

    sourceSets {
        commonMain.dependencies {
            // `api` rather than `implementation`: the iOS framework's
            // `export(project(":p2p-core"))` above requires the dependency to
            // be in the public API surface. It also matters for JVM/Android
            // consumers — `api` puts p2p-core's public types (P2pKit, Peer,
            // P2pSession, …) on their compile classpath, which the transport's
            // own public `lan()` DSL returns; `implementation` would hide them.
            api(project(":p2p-core"))
            implementation(libs.kotlinx.coroutines.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
        jvmMain.dependencies {
            implementation(libs.jmdns)
        }
        // Task #25 (v0.5): Android uses JmDNS instead of NsdManager to own the
        // mDNS cache in-process and unblock per-peer record invalidation that
        // the system NSD daemon does not expose. Pure-Java jar, no native
        // bits, so the same artifact as jvmMain.
        androidMain.dependencies {
            implementation(libs.jmdns)
        }
    }
}

// V0.4-PROVENANCE (L3) + AUDIT-2026-06: stamp BUILD_COMMIT.txt as the FINAL
// action of each per-config XCFramework assembly. Using the assembly task's
// own `doLast` (rather than a shared `finalizedBy` task) means the stamp is
// written ONLY when that assembly actually executes and SUCCEEDS:
//   • a `doLast` is skipped when the task FAILS — a `finalizedBy` runs even on
//     failure, which would stamp a failed/partial framework with the current
//     HEAD and let the Xcode freshness guard pass against a broken artifact;
//   • a `doLast` is skipped when the task is UP-TO-DATE — so a no-op rebuild
//     after HEAD moved no longer re-stamps an unchanged framework with a newer
//     commit (the old "freshness guard can lie" bug); and
//   • each task stamps ONLY the config it produced (release XOR debug), so a
//     debug-only assembly can't re-stamp a stale release dir, or vice-versa.
// The Xcode pre-build script reads this file to validate the deployed
// framework matches `git rev-parse HEAD` before the iOS app compiles.
afterEvaluate {
    val provenanceRootDir = rootProject.projectDir
    tasks.matching {
        it.name.startsWith("assemble") && it.name.contains("XCFramework")
    }.configureEach {
        val config = when {
            name.contains("Release") -> "release"
            name.contains("Debug") -> "debug"
            else -> null // umbrella aggregate task: per-config tasks stamp their own dir
        } ?: return@configureEach
        val outDir = layout.buildDirectory.dir("XCFrameworks/$config")
        doLast {
            fun git(vararg args: String): String = try {
                val p = ProcessBuilder("git", *args)
                    .directory(provenanceRootDir)
                    .redirectErrorStream(true)
                    .start()
                val out = p.inputStream.bufferedReader().readText().trim()
                if (p.waitFor() == 0) out else ""
            } catch (_: Exception) {
                ""
            }
            val commit = git("rev-parse", "HEAD").ifBlank { "unknown" }
            val dir = outDir.get().asFile
            if (dir.exists()) {
                dir.resolve("BUILD_COMMIT.txt").writeText(commit + "\n")
            }
        }
    }
}

// Maven publishing (fixes no-publishing-plugin / no-pom-metadata). See
// :p2p-core build for rationale. Auto-created KMP publications; POM enriched
// for Central-readiness; signing wired centrally in the root build (conditional
// on a PGP key being supplied).
publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name.set("P2pKit ${project.name}")
            description.set("P2pKit LAN transport — Bonjour/JmDNS discovery + TCP data over Network.framework/sockets.")
            url.set("https://github.com/Apdelrahman1911/P2pKit")
            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }
            developers {
                developer {
                    id.set("Apdelrahman1911")
                    name.set("Abdelrahman")
                }
            }
            scm {
                url.set("https://github.com/Apdelrahman1911/P2pKit")
                connection.set("scm:git:https://github.com/Apdelrahman1911/P2pKit.git")
                developerConnection.set("scm:git:ssh://git@github.com/Apdelrahman1911/P2pKit.git")
            }
        }
    }
}
