// Gradle wrapper for the iOS sample app. Lets Android Studio's Run button
// drive xcodebuild + xcrun simctl without leaving the IDE.
//
// No Kotlin / Android plugin is applied here — this subproject exists only
// to host Exec tasks that shell out to the Xcode toolchain. The actual
// Swift sources live next to this file; the Xcode project is generated by
// `xcodegen generate` (called automatically by the run script).

tasks.register<Exec>("runIosSimulator") {
    description = "Build the iOS sample, install on the iPhone simulator, and launch it."
    group = "p2pkit"
    // Make sure the XCFramework is fresh before xcodebuild consumes it.
    dependsOn(":p2p-transport-lan:assembleP2pKitSharedReleaseXCFramework")
    workingDir = rootDir
    commandLine("bash", "scripts/run-ios-app.sh")
    // Forward script stdout/stderr to the Gradle/Android Studio console so
    // the user can see xcodebuild progress and simctl launch results.
    standardOutput = System.out
    errorOutput = System.err
}

tasks.register<Exec>("regenerateXcodeProject") {
    description = "Re-run xcodegen against iosApp/project.yml."
    group = "p2pkit"
    workingDir = projectDir
    commandLine("xcodegen", "generate")
}
