import java.time.Instant

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.cryptography)
    `maven-publish`
}

cryptography {
    // cryptography-kotlin's CryptoKit provider is implemented through Swift
    // interop. Resolve the active Xcode toolchain rather than baking in an
    // /Applications/Xcode.app linker path.
    configureSwiftLinkerOpts = true
}

// V0.4-PROVENANCE (L1): generate a BuildInfo Kotlin object containing the
// current git commit / branch / dirty flag / build time. The constants are
// compiled into the framework binary, so they identify the artifact
// unambiguously regardless of how it was packaged. Wired into commonMain
// below via `kotlin.srcDir(generateBuildInfo)`.
//
// Up-to-date semantics: the task always runs (cheap, ~50ms), but only
// rewrites BuildInfo.kt when the content actually differs. That preserves
// Kotlin compile's incremental cache — downstream recompilation only
// happens when the commit / dirty flag / branch changes.
val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildinfo/commonMain/kotlin")
    outputs.dir(outputDir)
    outputs.upToDateWhen { false }
    val rootDir = rootProject.projectDir

    doLast {
        fun git(vararg args: String): String = try {
            val p = ProcessBuilder("git", *args)
                .directory(rootDir)
                .redirectErrorStream(true)
                .start()
            val out = p.inputStream.bufferedReader().readText().trim()
            if (p.waitFor() == 0) out else ""
        } catch (e: Exception) {
            ""
        }

        val commit = git("rev-parse", "HEAD").ifBlank { "unknown" }
        val short = if (commit != "unknown" && commit.length >= 7) commit.take(7) else commit
        val branch = git("rev-parse", "--abbrev-ref", "HEAD").ifBlank { "unknown" }
        val dirty = git("status", "--porcelain").isNotBlank()
        val buildTime = Instant.now().toString()

        val pkgDir = outputDir.get().asFile.resolve("dev/p2pkit/core")
        pkgDir.mkdirs()
        val outFile = pkgDir.resolve("BuildInfo.kt")
        val newContent = buildString {
            appendLine("// Generated by :p2p-core:generateBuildInfo. DO NOT EDIT.")
            appendLine("@file:Suppress(\"RedundantVisibilityModifier\")")
            appendLine()
            appendLine("package dev.p2pkit.core")
            appendLine()
            appendLine("/**")
            appendLine(" * Identity of the p2pkit framework binary the host app is running.")
            appendLine(" * Generated at build time from `git rev-parse HEAD`. Use [describe]")
            appendLine(" * for a single-line log signature.")
            appendLine(" */")
            appendLine("public object BuildInfo {")
            appendLine("    public const val COMMIT: String = \"$commit\"")
            appendLine("    public const val COMMIT_SHORT: String = \"$short\"")
            appendLine("    public const val BRANCH: String = \"$branch\"")
            appendLine("    public const val DIRTY: Boolean = $dirty")
            appendLine("    public const val BUILD_TIME: String = \"$buildTime\"")
            appendLine()
            appendLine("    public fun describe(): String =")
            appendLine("        \"p2pkit@\" + COMMIT_SHORT +")
            appendLine("            (if (DIRTY) \"-DIRTY\" else \"\") +")
            appendLine("            \" (\" + BRANCH + \", built \" + BUILD_TIME + \")\"")
            appendLine("}")
        }
        // Only write if content differs — preserves Kotlin compile's incremental cache.
        val oldContent = if (outFile.exists()) outFile.readText() else ""
        if (oldContent != newContent) {
            outFile.writeText(newContent)
        }
    }
}

kotlin {
    jvmToolchain(17)
    jvm()

    android {
        namespace = "dev.p2pkit.core"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    // Core types compile for iOS; the iOS LAN/TCP transport (Bonjour +
    // Network.framework) ships in :p2p-transport-lan's appleMain source set.
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.cryptography.core)
                api(libs.kotlinx.io.core)
            }
        }
        jvmMain.dependencies {
            implementation(libs.cryptography.provider.jdk)
            implementation(libs.bouncycastle.provider)
        }
        androidMain.dependencies {
            implementation(libs.cryptography.provider.jdk)
            implementation(libs.bouncycastle.provider)
        }
        iosMain.dependencies {
            implementation(libs.cryptography.provider.cryptokit)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

// Maven publishing (fixes no-publishing-plugin / no-pom-metadata). The KMP +
// Android-KMP-library plugins auto-create the per-target publications once
// `maven-publish` is applied; group/version come from the root `allprojects`
// block (dev.p2pkit / VERSION_NAME). We enrich the POM here so artifacts carry
// the metadata Maven Central requires. Signing is wired centrally in the root
// build (conditional on a PGP key being supplied), so local `publishToMavenLocal`
// stays keyless while a Central release just sets the signing properties.
publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name.set("P2pKit ${project.name}")
            description.set("P2pKit — cross-platform peer-to-peer local-network library (Android, iOS, JVM/desktop).")
            url.set("https://github.com/Apdelrahman1911/P2pKit")
            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }
            developers {
                developer {
                    id.set("Apdelrahman1911")
                    name.set("Abdelrahman")
                }
            }
            scm {
                url.set("https://github.com/Apdelrahman1911/P2pKit")
                connection.set("scm:git:https://github.com/Apdelrahman1911/P2pKit.git")
                developerConnection.set("scm:git:ssh://git@github.com/Apdelrahman1911/P2pKit.git")
            }
        }
    }
}
